[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = []
known_first_party = "circuitpython_latching_relay"
extra_standard_library = [
    "usb_hid",
    "network",
    "wifi",
    "board",
    "_pew",
    "gnss",
    "i2cperipheral",
    "pulseio",
    "storage",
    "pwmio",
    "neopixel_write",
    "audiobusio",
    "bitops",
    "audiocore",
    "fontio",
    "analogio",
    "sdioio",
    "_eve",
    "bitbangio",
    "framebufferio",
    "gamepad",
    "uheap",
    "_bleio",
    "rgbmatrix",
    "rtc",
    "alarm",
    "nvm",
    "camera",
    "aesio",
    "dualbank",
    "sdcardio",
    "socketpool",
    "audiomp3",
    "bitmaptools",
    "frequencyio",
    "usb_midi",
    "supervisor",
    "usb_cdc",
    "displayio",
    "memorymonitor",
    "_stage",
    "touchio",
    "_pixelbuf",
    "audiomixer",
    "sharpdisplay",
    "msgpack",
    "terminalio",
    "countio",
    "_typing",
    "audiopwmio",
    "digitalio",
    "multiterminal",
    "audioio",
    "ps2io",
    "rotaryio",
    "microcontroller",
    "busio",
    "vectorio",
    "wiznet",
    "watchdog",
    "canio",
    "ustack",
    "gamepadshift",
    "binascii",
    "errno",
    "ulab",
]
